# Generated by Django 3.0.7 on 2021-08-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.TextField()),
                ('img', models.FileField(upload_to='pic/%y/')),
            ],
        ),
    ]
